echo off
CALL ASMSHADER BasicColor
CALL ASMSHADER BNPTexture
CALL ASMSHADER NoTransformDebug
CALL ASMSHADER NoTransformTexture
CALL ASMSHADER TestTexture
CALL ASMSHADER Texture
CALL ASMSHADER WaterVertex

CALL ASMSHADER DirectionalLight
CALL ASMSHADER DirectionalLightPixel
CALL ASMSHADER DirectionalLightTexture
CALL ASMSHADER DirectionalLightMultiTexture

CALL ASMSHADER DebugShader

CALL ASMSHADER FunstonSphericalHarmonics
CALL ASMSHADER FunstonSphericalHarmonicsRim
CALL ASMSHADER FunstonSphericalHarmonicsRimVertex
CALL ASMSHADER FunstonSphericalHarmonicsNegRim
CALL ASMSHADER FunstonSHDoubleRim
CALL ASMSHADER FunstonSHInverseRim
CALL ASMSHADER FunstonSHNegInvRim
CALL ASMSHADER FunstonSphericalHarmonicsLM
CALL ASMSHADER FunstonSHLMRim

CALL ASMSHADER Anaglyph

CALL ASMSHADER Caustics

CALL ASMSHADER MultiTexture

CALL ASMSHADER BasicRim

CALL ASMSHADER TexturedRim
CALL ASMSHADER TexturedInverseRim

CALL ASMSHADER DirectionalLightMultiTextureRim
CALL ASMSHADER DirectionalLightInvRimTexture
CALL ASMSHADER DirectionalLightRimTexture
CALL ASMSHADER DirectionalLightRim

CALL ASMSHADER Terrain
CALL ASMSHADER TerrainTexture
CALL ASMSHADER TerrainLightMap
CALL ASMSHADER TerrainLightMap1C
CALL ASMSHADER TerrainLightMap2C
CALL ASMSHADER TerrainLightMapNC
CALL ASMSHADER TerrainLightMapVertex





