enum {
	STATE_MAINMENU, // 0
	STATE_BRAID,	// 1
	STATE_BROWSER, // 2
	STATE_TRITEST1, // 3
	STATE_MANY, // 4

	STATE_NEWCARENALOBBY, // 5
	STATE_NEWCARENACONNECT, // 6
	STATE_NEWCARENAOLDCONS, // 7
	STATE_NEWCARENANEWCONS, // 8
	STATE_NEWCARENASTATUS, // 9

	STATE_NEWCARENAGAME, // 10
	STATE_PLAYMOVIE, // 11
	STATE_MARCHINGCUBESTEST, // 12
	STATE_PLOTTER, // 13
	STATE_MATCHSERVER, // 14

	STATE_MATCHLOGON, // 15
	STATE_MATCHLOBBY, // 16
	STATE_MATCHRESULTS, // 17
	STATE_MATCHHISCORES, // 18
	STATE_MATCHPICKGAME, // 19

	STATE_MATCHOPTIONS, // 20
	STATE_MATCHQUICKGAME, // 21
	STATE_MATCHGAME1, // 22
	STATE_MATCHREGISTER, // 23
	STATE_MATCHPICKSERVER, // 24

	STATE_MATCHTITLE, // 25
	STATE_NEWTONS, // 26
	STATE_MAZE, // 27
	STATE_MATTEST, // 28
	STATE_MATTEST2, // 29

	STATE_LIGHTUP, // 30
	STATE_RIEMANN, // 31

	STATE_NUM, // 32
};
