#define INCLUDE_WINDOWS
#include <m_eng.h>

// meant to be called from outside the mainmenu (plus and minus key)
U32 changeglobalxyres(/*S32 oldx,S32 oldy,*/S32 direction/*,S32* newx,S32* newy*/) {
	S32 gxy=videoinfo.gamexyidx;
	if (direction!=-1 && direction!=1)
		return 0;
	if (videoinfo.ngamexy<2)
		return 0;
	gxy+=direction;
	if (gxy>=videoinfo.ngamexy)
		return 0;
	if (gxy<0)
		return 0;
	videoinfo.gamexyidx=gxy;
	return 1;
}

U32 setglobalxyres(S32 idx) // set globalxyres index, calcs globalxres,globalyres
{
	S32 gxy=videoinfo.gamexyidx;
	if (videoinfo.ngamexy<2)
		return 0;
	gxy=idx;
	if (gxy>=videoinfo.ngamexy)
		return 0;
	if (gxy<0)
		return 0;
	videoinfo.gamexyidx=gxy;
	return 1;
}

void load_device()
{
	S32 i;
	pushandsetdir("config");
	script sc("gamexy.txt");
	videoinfo.ngamexy=0;
	for (i=0;i<sc.num();++i) {
		if (!strcmp(sc.idx(i).c_str(),"gamexy")) {
			if (videoinfo.ngamexy<MAXXYRES) {
				videoinfo.gamexy[videoinfo.ngamexy].x=atoi(sc.idx(i+1).c_str());
				videoinfo.gamexy[videoinfo.ngamexy].y=atoi(sc.idx(i+2).c_str());
				++videoinfo.ngamexy;
			}
			i+=2;
		} else
			errorexit("unknown gamexy.txt command \"%s\"",sc.printidx(i).c_str());
	}
	loadconfigfile("device.txt",wininfovars,nwininfovars);
	if (wininfo.wantedvideomaindriver < 0) // make it so you don't have to modify or delete this file to GO!
		wininfo.wantedvideomaindriver = 0;
	popdir();
}

void set_device()
{
	video_init(wininfo.wantedvideomaindriver,wininfo.wantedvideosubdriver);
	input_init(wininfo.wantedusedirectinput);
	audio_init(wininfo.wantedaudiomaindriver,wininfo.wantedaudiosubdriver,wininfo.wantedaudiomicsubdriver);
}

void save_device()
{
	FILE* fw;
	pushandsetdir("config");
	fw=fopen2("device.txt","w");
	if (fw) {
		fprintf(fw,"# generated by engq...\n\n");
		fprintf(fw,"wantedvideomaindriver %d # -1 none, 0 gdi, 1 directdraw, 2 direct3d window, 3 direct3d fullscreen\n",
			videoinfo.video_maindriver);
		fprintf(fw,"wantedvideosubdriver %d # 0 subdevice 0 ati rage pro, 1 subdevice 1 voodoo 2 etc.\n",
			videoinfo.video_subdriver);
		fprintf(fw,"wantedaudiomaindriver %d # -1 none, 0 waveplayer, 1 directsound\n",
			audioinfo.audio_maindriver);
		fprintf(fw,"wantedaudiosubdriver %d # 0 subdevice 0 RipTide Playback, 1 subdevice 1 Game Compatible Device etc.\n",
			audioinfo.audio_subdriver);
		fprintf(fw,"wantedaudiomicsubdriver %d # 0 subdevice for mic\n",
			audioinfo.audio_micsubdriver);
		fprintf(fw,"wantedusedirectinput %d # -1 none (later), 0 message based, 1 directinput (keyboard, mouse and joystick)\n",
			wininfo.usedirectinput);
		fprintf(fw,"mousemode %d # 0 normal, 1 infinite\n",
			wininfo.mousemode);
		fprintf(fw,"gamexyidx %d # global game pixel resolution (gamexy) index\n",
			videoinfo.gamexyidx);
		fprintf(fw,"texreduce %d # reduce texture resolution\n",
			videoinfo.texreduce);
		fclose(fw);
	}
	popdir();
	
}
